---
title: "p8131_hw4_jsg2145"
author: "Jared Garfinkel"
date: "2/20/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(nnet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
df_low = tibble(
  conx = rep(c("low", "high"), 3),
  hous_tp = rep(c("tr_bk", "apt", "hous"), each = 2),
  values = c(65, 34, 130, 141, 67, 130)
) %>% 
  mutate(sat = "low")

df_med = tibble(
  conx = rep(c("low", "high"), 3),
  hous_tp = rep(c("tr_bk", "apt", "hous"), each = 2),
  values = c(54, 47, 76, 116, 48, 105)
) %>% 
  mutate(sat = "med")

df_high = tibble(
  conx = rep(c("low", "high"), 3),
  hous_tp = rep(c("tr_bk", "apt", "hous"), each = 2),
  values = c(100, 100, 111, 191, 62, 104)
) %>% 
  mutate(sat = "high")

df_sum = union(df_low, df_med) %>% 
  union(df_high) %>% 
  unnest() %>% 
  pivot_wider(names_from = sat, values_from = values) %>% 
  group_by(conx, hous_tp) %>% 
  mutate(n = sum(low, med, high))

df_tbl = df_sum %>% 
  group_by(conx, hous_tp) %>% 
  summarize(low_pct = round(low/n*100, digits = 0),
            med_pct = round(med/n*100, digits = 0),
            high_pct = round(high/n*100, digits = 0)
  )
```

```{r}
df_tbl %>% knitr::kable()
```

```{r}
df_tidy_tbl = df_tbl %>% 
  pivot_longer(cols = c(low_pct, med_pct, high_pct), names_to = "sat", values_to = "pct") %>% 
  ungroup() %>% 
  mutate(sat = str_remove(sat, "_pct$"),
         sat = factor(sat, labels = c("low", "med", "high")),
         conx = factor(conx, labels = c("low", "high")))  
  
```


```{r}
df_tidy_tbl %>% 
  ggplot(aes(x = sat, y = pct)) +
  geom_col() +
  scale_fill_brewer(palette = "Blues") +
  facet_grid(hous_tp~conx)
```

```{r}
hagen.multi = multinom(cbind(low, med, high)~hous_tp+conx, data = df_sum)

summary(hagen.multi)
```

```{r}
pihat = predict(hagen.multi, type = "probs") 
m = rowSums(df_sum[3:5])
res.pearson = (df_sum[3:5] - pihat * m) / sqrt(pihat * m)
```

```{r}
G.stat = sum(res.pearson ^ 2) # Generalized Pearson Chisq Stat
G.stat
pval = 1 - pchisq(G.stat, df = (6 - 4) * (3 - 1))
pval
```


The p-value is `r pval`, so we do not reject the null, indicating the fit is acceptable.
